//only used for poedit to find translatable strings
let keywords = [ 
    _('A Firelit Room'),
    _("A Raucous Village"),
    _("A Large Village"),
    _("A Modest Village"),
    _("A Tiny Village"),
    _("A Lonely Hut"),
    _("A Silent Forest"),
    _("check traps"),
    _("A Dusty Path"),

		_('wood'),
		_('builder'),
		_('teeth'),
		_('meat'),
		_('fur'),
		_('alien alloy'),
		_('bullets'),
		_('charm'),
		_('leather'),
		_('iron'),
		_('steel'),
		_('coal'),
		_('sulphur'),
		_('energy cell'),
		_('torch'),
		_('medicine'),
		_('hunter'),
		_('trapper'),
		_('tanner'),
		_('grenade'),
		_('bolas'),
		_('bayonet'),
		_('charcutier'),
		_('iron miner'),
		_('iron mine'),
		_('coal miner'),
		_('coal mine'),
		_('sulphur miner'),
		_('sulphur mine'),
		_('armourer'),
		_('steelworker'),
		_('bait'),
		_('cured meat'),
		_('scales'),
		_('compass'),
		_('laser rifle'),
		_('gatherer'),
		_('cloth'),
		_('scales'),
		_('cured meat'),
		_('thieves'),
		_('not enough fur'),
		_('not enough wood'),
		_('not enough coal'),
		_('not enough iron'),
		_('not enough steel'),
		_('not enough sulphur'),
		_('baited trap'),
		_('not enough scales'),
		_('not enough cloth'),
		_('not enough teeth'),
		_('not enough leather'),
		_('not enough meat'),
		_('the compass points east'),
		_('the compass points west'),
		_('the compass points north'),
		_('the compass points south'),
		_('the compass points northeast'),
		_('the compass points northwest'),
		_('the compass points southeast'),
        _('the compass points southwest'),
        
        _('village'),
        _('forest'),
		_('population'),
		
		_('dry brush and dead branches litter the forest floor'),
		_('the traps contain'),
		_(' and '),
		_('a stranger arrives in the night'),
		_('a weathered family takes up in one of the huts.'),
		_('a small group arrives, all dust and bones.'),
		_('a convoy lurches in, equal parts worry and hope.'),
		_('the town\'s booming. word does get around.'),

		_('dead'),
		_('smoldering'),
		_('flickering'),
		_('burning'),
		_('roaring'),
		_('freezing'),
		_('cold'),
		_('mild'),
		_('warm'),
		_('hot'),
		_('builder just shivers'),
		_('the wood has run out'),
		_('the stranger shivers, and mumbles quietly. her words are unintelligible.'),
		_('a ragged stranger stumbles through the door and collapses in the corner'),
		_('the stranger in the corner stops shivering. her breathing calms.'),
		_('the wind howls outside'),
		_('the wood is running out'),
		_('the light from the fire spills from the windows, out into the dark'),
		_('the fire is {0}'),
		_('the room is {0}'),
		_('the traps contain ')
]; 

keywords = null;